displayName: Auto Start Middleware
type: middleware
import: github.com/ksmarty/traefik-container-sleep

summary: Automatically starts Docker containers on incoming HTTP requests and stops them after inactivity.

testData:
  timeout: 30
  url: "http://controller:5000/wake"